api:
  gql: https://api.data.gov/TEST/10x-imls/v1/graphql/
  events: https://api.data.gov/TEST/10x-imls/v1/search/events/
  wifi: https://api.data.gov/TEST/10x-imls/v1/search/wifi/
filters:
  # minimum number of minutes a patron must be present to be counted
  minimum: 30
  # max before we think you're a robot
  maximum: 480
  stepsize: 10000